apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lcjpy4ldh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lcjpy4ldh-go 
  name: lcjpy4ldh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lcjpy4ldh-go 
